//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TestXafSolution.Module.TestWork2
{

    public partial class Cargo : XPLiteObject
    {
        int fNumber;
        [Key]
        public int Number
        {
            get { return fNumber; }
            set { SetPropertyValue<int>("Number", ref fNumber, value); }
        }
        string fName;
        [Size(10)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        Area fNumber_Area;
        [Association(@"CargoReferencesArea")]
        public Area Number_Area
        {
            get { return fNumber_Area; }
            set { SetPropertyValue<Area>("Number_Area", ref fNumber_Area, value); }
        }
        int fWeight;
        public int Weight
        {
            get { return fWeight; }
            set { SetPropertyValue<int>("Weight", ref fWeight, value); }
        }
        DateTime fCreate_Cargo;
        public DateTime Create_Cargo
        {
            get { return fCreate_Cargo; }
            set { SetPropertyValue<DateTime>("Create_Cargo", ref fCreate_Cargo, value); }
        }
        DateTime fDelete_Cargo;
        public DateTime Delete_Cargo
        {
            get { return fDelete_Cargo; }
            set { SetPropertyValue<DateTime>("Delete_Cargo", ref fDelete_Cargo, value); }
        }
    }

}
