//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TestXAF.Module.BusinessObjects.TestWork
{

    public partial class Area : XPLiteObject
    {
        int fNumber;
        [Key(true)]
        public int Number
        {
            get { return fNumber; }
            set { SetPropertyValue<int>("Number", ref fNumber, value); }
        }
        string fName;
        [Size(20)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        Store fNumber_Store;
        [Association(@"AreaReferencesStore")]
        public Store Number_Store
        {
            get { return fNumber_Store; }
            set { SetPropertyValue<Store>("Number_Store", ref fNumber_Store, value); }
        }
        DateTime fCreate_Area;
        public DateTime Create_Area
        {
            get { return fCreate_Area; }
            set { SetPropertyValue<DateTime>("Create_Area", ref fCreate_Area, value); }
        }
        DateTime fDelete_Area;
        public DateTime Delete_Area
        {
            get { return fDelete_Area; }
            set { SetPropertyValue<DateTime>("Delete_Area", ref fDelete_Area, value); }
        }
        [Association(@"CargoReferencesArea")]
        public XPCollection<Cargo> Cargoes { get { return GetCollection<Cargo>("Cargoes"); } }
        [Association(@"PicketReferencesArea")]
        public XPCollection<Picket> Pickets { get { return GetCollection<Picket>("Pickets"); } }
    }

}
