//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
namespace TestXAF.Module.BusinessObjects.TestWork
{

    public partial class Cargo : XPLiteObject
    {
        int fNumber;
        [Key]
        public int Number
        {
            get { return fNumber; }
            set { SetPropertyValue<int>("Number", ref fNumber, value); }
        }
        string fName;
        [Size(10)]
        public string Name
        {
            get { return fName; }
            set { SetPropertyValue<string>("Name", ref fName, value); }
        }
        double fWeight;
        public double Weight
        {
            get { return fWeight; }
            set { SetPropertyValue<double>("Weight", ref fWeight, value); }
        }
        Area fNumberArea;
        [Association(@"CargoReferencesArea")]
        public Area NumberArea
        {
            get { return fNumberArea; }
            set { SetPropertyValue<Area>("NumberArea", ref fNumberArea, value); }
        }
        DateTime fCreate;
        public DateTime Create
        {
            get { return fCreate; }
            set { SetPropertyValue<DateTime>("Create", ref fCreate, value); }
        }
        DateTime fDelete1;
        [Persistent(@"Delete")]
        public DateTime Delete1
        {
            get { return fDelete1; }
            set { SetPropertyValue<DateTime>("Delete1", ref fDelete1, value); }
        }
    }

}
